DROP TABLE EDUOFF;

CREATE TABLE EDUOFF(
COURSE_ID VARCHAR2(500) PRIMARY KEY NOT NULL, -- 강의ID
COURSE_NM VARCHAR2(500), --강의명
COURSE_GUBUN VARCHAR2(20), --강의구분
COURSE_REQUEST_STR_DT VARCHAR2(500),  --신청시작일
COURSE_REQUEST_END_DT VARCHAR2(500),  --신청종료일
COURSE_STR_DT VARCHAR2(500),  --교육시작일
COURSE_END_DT VARCHAR2(500),  --교육종료일
COURSE_TARGET VARCHAR2(100), --학습대상
CAPACITY VARCHAR2(500),   --정원
COURSE_APPLY_URL VARCHAR2(2000) --수강신청 URL
);

SELECT * FROM EDUOFF;