--DB
--자유게시판(답글)

DROP SEQUENCE FREETABLE_NO_SEQ;
DROP SEQUENCE FREETABLE_GROUPNO_SEQ;
DROP TABLE FREETABLE;

CREATE SEQUENCE FREETABLE_NO_SEQ;
CREATE SEQUENCE FREETABLE_GROUPNO_SEQ;


--글번호, ID, 제목, 내용, 작성일, 조회수(0부터)
--그룹번호, 그룹순서(1부터), 제목탭(0부터), 삭제여부(Y/N)


CREATE TABLE FREETABLE(
   FREETABLE_NO NUMBER NOT NULL,
   FREETABLE_ID VARCHAR2(500) NOT NULL,
   FREETABLE_TITLE VARCHAR2(2000) NOT NULL, 
   FREETABLE_CONTENT VARCHAR2(4000) NOT NULL,
   FREETABLE_REGDATE VARCHAR2(500) NOT NULL,     --작성일
   FREETABLE_READCOUNT NUMBER NOT NULL,          --조회수(0부터)
   FREETABLE_GROUPNO NUMBER NOT NULL,            --그룹번호
   FREETABLE_STEP NUMBER NOT NULL,               --그룹순서(1부터)
   FREETABLE_TITLETAB NUMBER NOT NULL,           --제목탭(0부터)
   FREETABLE_DELFLAG VARCHAR2(2) NOT NULL,       --삭제여부(Y/N)
    
   CONSTRAINT FREETABLE_NO_PK PRIMARY KEY (FREETABLE_NO),
   CONSTRAINT FREETABLE_DELFLAG_CHK CHECK(FREETABLE_DELFLAG IN ('Y','N'))
  );

SELECT * FROM FREETABLE ORDER BY FREETABLE_GROUPNO DESC, FREETABLE_STEP;

DELETE FROM FREETABLE WHERE FREETABLE_NO = 47;

--첫번째 글
INSERT INTO FREETABLE 
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'관리자','첫번째 글입니다.','테스트 내용',SYSDATE,0,
FREETABLE_GROUPNO_SEQ.NEXTVAL,1,0,'N');

--두번째 글
INSERT INTO FREETABLE 
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'이순신','두번째 글입니다.','테스트 내용',SYSDATE,0,
FREETABLE_GROUPNO_SEQ.NEXTVAL,1,0,'N');

--두번째 글에 대한 답글 1
INSERT INTO FREETABLE 
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'관리자','RE:두번째 글입니다.','답글테스트',SYSDATE,0,
(SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=2),
(SELECT FREETABLE_STEP+1 FROM FREETABLE WHERE FREETABLE_NO=2),
(SELECT FREETABLE_TITLETAB+1 FROM FREETABLE WHERE FREETABLE_NO=2),
'N'
);

--첫번째 글에 대한 답글 1
INSERT INTO FREETABLE
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'홍길동','RE:첫번째 글입니다.','답글테스트',SYSDATE,0,
(SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=1),
(SELECT FREETABLE_STEP+1 FROM FREETABLE WHERE FREETABLE_NO=1),
(SELECT FREETABLE_TITLETAB+1 FROM FREETABLE WHERE FREETABLE_NO=1),
'N'
);

--(두번째 글에 대한 답글 1)에 대한 답글 1
INSERT INTO FREETABLE
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'홍길동','RE:RE:두번째 글입니다.','답글테스트',SYSDATE,0,
(SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=3),
(SELECT FREETABLE_STEP+1 FROM FREETABLE WHERE FREETABLE_NO=3),
(SELECT FREETABLE_TITLETAB+1 FROM FREETABLE WHERE FREETABLE_NO=3),
'N'
);

--두번째글에 대한 답글 2 : 부모랑 같은 GROUPNO, 부모의 STEP보다 큰 글들의 STEP을 +1
UPDATE FREETABLE SET FREETABLE_STEP=FREETABLE_STEP+1
WHERE FREETABLE_GROUPNO = (SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=2) AND 
FREETABLE_STEP > (SELECT FREETABLE_STEP FROM FREETABLE WHERE FREETABLE_NO=2);

INSERT INTO FREETABLE
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'이순신','RE:두번째 글입니다.','답글테스트',SYSDATE,0,
(SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=2),
(SELECT FREETABLE_STEP+1 FROM FREETABLE WHERE FREETABLE_NO=2),
(SELECT FREETABLE_TITLETAB+1 FROM FREETABLE WHERE FREETABLE_NO=2),
'N'
);

--(두번째글에 대한 답글 2) 에 대한 답글 1
UPDATE FREETABLE SET FREETABLE_STEP=FREETABLE_STEP+1
WHERE FREETABLE_GROUPNO = (SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=6) AND 
FREETABLE_STEP > (SELECT FREETABLE_STEP FROM FREETABLE WHERE FREETABLE_NO=6);

INSERT INTO FREETABLE
VALUES(FREETABLE_NO_SEQ.NEXTVAL,'관리자','RE:RE:두번째 글입니다.','답글테스트',SYSDATE,0,
(SELECT FREETABLE_GROUPNO FROM FREETABLE WHERE FREETABLE_NO=6),
(SELECT FREETABLE_STEP+1 FROM FREETABLE WHERE FREETABLE_NO=6),
(SELECT FREETABLE_TITLETAB+1 FROM FREETABLE WHERE FREETABLE_NO=6),
'N'
);

--페이징 (ROWNUM)
SELECT M.*
FROM (SELECT ROWNUM AS "RW", A.* FROM (SELECT * FROM FREETABLE ORDER BY FREETABLE_GROUPNO DESC, FREETABLE_STEP) A) M
WHERE RW BETWEEN 11 AND 20



--자유게시판(댓글,대댓글)------------

DROP SEQUENCE FREECOMM_NO_SEQ;
DROP SEQUENCE FREECOMM_GROUPNO_SEQ;
DROP TABLE FREECOMM;

CREATE SEQUENCE FREECOMM_NO_SEQ;
CREATE SEQUENCE FREECOMM_GROUPNO_SEQ;

CREATE TABLE FREECOMM(
   FREETABLE_NO NUMBER NOT NULL REFERENCES FREETABLE(FREETABLE_NO) ON DELETE CASCADE,
   FREECOMM_NO NUMBER PRIMARY KEY,
   FREECOMM_ID VARCHAR2(500) NOT NULL,
   FREECOMM_CONTENT VARCHAR2(2500) NOT NULL,
   FREECOMM_REGDATE VARCHAR2(500) NOT NULL,     --작성일
   FREECOMM_GROUPNO NUMBER NOT NULL,            --그룹번호
   FREECOMM_STEP NUMBER NOT NULL,               --그룹순서(1부터)
   FREECOMM_TITLETAB NUMBER NOT NULL           --제목탭(0부터)  
   );
   
  
SELECT * FROM FREECOMM;
  
SELECT * FROM FREECOMM ORDER BY FREECOMM_GROUPNO DESC, FREECOMM_STEP;



INSERT INTO FREECOMM VALUES(
1,FREECOMM_NO_SEQ.NEXTVAL,'관리자','첫번째 글입니다',SYSDATE,
FREECOMM_GROUPNO_SEQ.NEXTVAL,1,0
);

INSERT INTO FREECOMM VALUES(
1,FREECOMM_NO_SEQ.NEXTVAL,'홍길동','ㄴ첫번째 글의 답글 입니다.',SYSDATE,
(SELECT FREECOMM_GROUPNO FROM FREECOMM WHERE FREECOMM_NO=1),
(SELECT FREECOMM_STEP+1 FROM FREECOMM WHERE FREECOMM_NO=1),
(SELECT FREECOMM_TITLETAB+1 FROM FREECOMM WHERE FREECOMM_NO=1)
);
  
SELECT FREECOMM_NO,FREECOMM_ID,FREECOMM_CONTENT,FREECOMM_REGDATE FROM FREECOMM WHERE FREECOMM_NO=1;