CREATE SEQUENCE NOTICEBOARDSEQ;

CREATE TABLE NOTICEBOARD (
NOTICEBOARD_NO NUMBER PRIMARY KEY,
NOTICEBOARD_WRITER VARCHAR2(100),
NOTICEBOARD_TITLE VARCHAR2(300),
NOTICEBOARD_CONTENT VARCHAR2(500),
NOTICEBOARD_REGDATE DATE,
NOTICEBOARD_COUNT NUMBER
);


INSERT INTO NOTICEBOARD VALUES('1','관리자','제목','내용',SYSDATE,0);
INSERT INTO NOTICEBOARD VALUES(NOTICEBOARDSEQ.NEXTVAL,'관리자1','제목1','내용1',SYSDATE,0);

SELECT * FROM NOTICEBOARD;
